using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class RoomLayouts
{
    public static List<List<List<string>>> NormalRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "D"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "G"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "G", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "G", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "G", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        },
    };

    public static List<List<List<string>>> ShopRoomLayouts = new List<List<List<string>>>(){ 
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "S", "N", "N", "N", "N", "N", "N", "S", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "S", "N", "N", "N", "S", "N", "N", "N", "N", "S", "N", "N", "N", "S", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
                new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "S", "N", "N", "N", "N", "N", "N", "S", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "S", "N", "N", "N", "S", "N", "N", "N", "N", "S", "N", "N", "N", "S", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "S", "N", "N", "N", "N", "N", "N", "S", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "S", "N", "N", "N", "S", "N", "N", "N", "N", "S", "N", "N", "N", "S", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "S", "N", "N", "N", "N", "N", "N", "S", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "S", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "S", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "S", "N", "N", "N", "S", "N", "N", "N", "N", "S", "N", "N", "N", "S", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> TreasureRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "T", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "T", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "T", "N", "N", "N", "N", "N", "N", "N", "N", "T", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "T", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "T", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> HospitalRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "H", "H", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "H", "H", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "H", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "H", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "H", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "H", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "H", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "H", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> BossRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "B", "N", "N", "E", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "B", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "B", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "E", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "E", "N", "N", "N", "B", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "E", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "B", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        }
    };



}
