using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class RoomLayouts
{
    public static List<List<List<string>>> NormalRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "D"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "G"},
        new List<string>(){ "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "D", "D", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "G", "N", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "G", "G", "G", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "D", "D", "N", "N", "N", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "D", "D", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "G", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G"},
        new List<string>(){ "D", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "D", "D", "G", "G", "G", "G", "G", "G", "G"},
        },

        new List<List<string>>(){
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N", "N", "G", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N"},
        new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "D"},
        new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "G"},
        new List<string>(){ "G", "N", "N", "N", "N", "G", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G"},
        new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "N", "N", "G", "G", "G", "G", "G", "G", "G"},
        },

    };



}
