using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class RoomLayouts
{
    public static List<List<List<string>>> NormalRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "2", "N", "N", "N", "N", "N", "N", "G"},
            new List<string>(){ "N", "N", "N", "N", "G", "N", "N", "3", "G"},
            new List<string>(){ "N", "N", "N", "G", "G", "N", "N", "G", "G"},
            new List<string>(){ "D", "N", "N", "G", "N", "N", "N", "G", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "G", "G"},
            new List<string>(){ "1", "N", "N", "N", "N", "N", "G", "G", "G"},
            new List<string>(){ "N", "N", "0", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "D", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "2", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "G", "G", "N", "N", "3", "N"},
            new List<string>(){ "1", "N", "G", "G", "G", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "G", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "N", "N", "N", "N", "N", "G", "N", "G"},
            new List<string>(){ "G", "G", "0", "N", "G", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "G", "2", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "1", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "G", "G", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "3", "N"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "0", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "D", "G", "G", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "N", "2", "N", "N", "G", "G", "G"},
            new List<string>(){ "G", "N", "N", "N", "N", "N", "N", "N", "G"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "1", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "G", "G", "N", "N", "3", "N"},
            new List<string>(){ "N", "N", "G", "G", "N", "N", "0", "N", "N"},
            new List<string>(){ "N", "G", "G", "G", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "G", "D", "N", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "G", "N", "3", "G", "G"},
            new List<string>(){ "G", "G", "1", "G", "G", "N", "N", "N", "G"},
            new List<string>(){ "G", "2", "G", "G", "N", "N", "N", "N", "G"},
            new List<string>(){ "D", "N", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "G", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "N", "G", "G", "G", "N", "N", "N", "G"},
            new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "D", "0", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "G", "2", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "G", "G", "G", "N", "N", "3", "N"},
            new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "G", "N", "N", "N", "N", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "G"},
            new List<string>(){ "1", "N", "N", "N", "N", "N", "G", "G", "G"},
            new List<string>(){ "N", "N", "N", "0", "N", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "G", "G", "G"},
            new List<string>(){ "N", "2", "N", "N", "N", "N", "N", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "3", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "N", "G"},
            new List<string>(){ "N", "1", "N", "N", "N", "N", "G", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "0", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "G", "G", "D", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "N", "D", "N", "G", "G", "G"},
            new List<string>(){ "G", "G", "2", "N", "N", "N", "N", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "N", "N", "3", "G"},
            new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "N", "N", "D"},
            new List<string>(){ "G", "1", "G", "G", "G", "G", "G", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "N"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "0", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "N", "N"},
            new List<string>(){ "N", "2", "G", "G", "G", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "G", "G", "N", "3", "N"},
            new List<string>(){ "N", "N", "N", "G", "G", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "G"},
            new List<string>(){ "G", "1", "G", "N", "N", "N", "G", "G", "G"},
            new List<string>(){ "G", "G", "0", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "D", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "G", "G", "G", "G", "N", "N", "N", "N"},
            new List<string>(){ "N", "2", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "G", "G", "G", "N", "N", "3", "N"},
            new List<string>(){ "N", "N", "N", "G", "G", "G", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "G", "G", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "G", "G", "N", "N", "N", "N", "G"},
            new List<string>(){ "N", "1", "G", "G", "N", "N", "G", "G", "G"},
            new List<string>(){ "N", "G", "G", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "0", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "N", "2", "N", "N", "N", "N", "N", "G", "G"},
            new List<string>(){ "1", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "G", "G", "N", "N", "N", "N", "3", "N", "G"},
            new List<string>(){ "G", "G", "N", "N", "N", "N", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "D", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "G", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "3", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "2", "G", "G"},
            new List<string>(){ "N", "N", "N", "N", "N", "G", "G", "G", "N"},
            new List<string>(){ "N", "N", "G", "N", "N", "N", "G", "N", "N"},
            new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "1", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "0", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "G", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "2", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "G", "G", "G", "G", "3", "G", "G"},
            new List<string>(){ "D", "N", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "N", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "0", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "1", "G", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "N", "G", "G", "G", "N", "G", "G", "3", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "N", "2", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "G", "G", "G", "N"},
            new List<string>(){ "N", "N", "G", "N", "N", "N", "G", "N", "N"},
            new List<string>(){ "N", "G", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "1", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "G", "0", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "G", "G", "G", "G", "G", "G", "G", "G", "G"},
            new List<string>(){ "G", "G", "G", "G", "N", "G", "G", "3", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "N", "2", "G", "G"},
            new List<string>(){ "G", "G", "G", "N", "N", "G", "G", "N", "N"},
            new List<string>(){ "G", "G", "G", "N", "N", "N", "G", "N", "D"},
            new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "1", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "0", "G", "N", "N", "N", "N", "N"},
            new List<string>(){ "G", "G", "G", "G", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> ShopRoomLayouts = new List<List<List<string>>>(){ 
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S2", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S3", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S2", "N", "N", "N", "S1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S2", "N", "N", "N", "N", "N", "S1", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S1", "N", "N", "N", "N", "N", "S2", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S3", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S0", "N", "N", "N", "N", "N", "S3", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S1", "N", "N", "N", "N", "N", "S3", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S2", "N", "N", "N", "S1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S3", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S0", "N", "N", "N", "N", "N", "S3", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S1", "N", "N", "N", "N", "N", "S2", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S3", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S3", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S0", "N", "N", "N", "S2", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "S1", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S0", "N", "N", "N", "N", "N", "S3", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S1", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "S3", "N", "N", "N", "S2", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "S0", "N", "N", "N", "N", "N", "S1", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> TreasureRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "M0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "M0", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "M0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "M0", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> DoubleTreasureRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "M0", "N", "N", "N", "M1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "M0", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "M1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "M0", "N", "N", "N", "M1", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "M1", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "M0", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };


    public static List<List<List<string>>> HospitalRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "H", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "H", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "H", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "H", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> BossRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "B3", "N", "E", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "E", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "B2", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "E", "N", "B1", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "B0", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "E", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };

    public static List<List<List<string>>> StartRoomLayouts = new List<List<List<string>>>(){
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "R", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "D", "N", "N", "N", "N", "N", "N", "R", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "R", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "R", "N", "N", "N", "N", "N", "R", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "R", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "R", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "R", "N", "N", "N", "R", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "D", "N", "N", "N", "N"},
        },
        new List<List<string>>(){
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "R", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "R", "N", "N", "N", "N", "N", "N", "D"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "R", "N", "N", "N", "N", "N"},
            new List<string>(){ "N", "N", "N", "N", "N", "N", "N", "N", "N"},
        },
    };



}
